apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RoleBinding
metadata:
  name: restrictive-role-bind
  namespace: monitoring
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restrictive-cluster-role
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: system:authenticated
